version: "3"

services:

   portainer1:
      container_name: portainer1
      image: portainer/portainer-ce

      restart: always
      logging:
         driver: "json-file"
         options:
            max-file: "5"
            max-size: 10m

      ports:
         - "9001:9000"

      volumes:
         - /var/run/docker.sock:/var/run/docker.sock         
         - ./data:/data
